name: Publish Issues

on:
  push:
    paths:
      - 'issues/*.md'

permissions:
  contents: read
  issues: write

jobs:
  publish_issues:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 确保能访问上一个提交

      - name: 📂 获取本次提交变更的 issues/*.md 文件
        id: get_changed_files
        run: |
          echo "🔍 当前 GITHUB_SHA: $GITHUB_SHA"
          echo "📋 当前提交变更文件列表："
          git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA"

          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA" | grep '^issues/.*\.md$' || true)

          echo "📂 本次获取到的md文件：$CHANGED_FILES"

          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 📝 创建或更新 Issues
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "📂 开始处理 issues/*.md 文件"

          for file in $CHANGED_FILES; do
            echo "📄 处理文件: $file"

            TITLE=$(basename "$file" .md | sed 's/[-_]/ /g')
            echo "🔍 检查是否已有同名 issue: '$TITLE'"

            # 提取标签
            LABELS_LINE=$(grep '^ISSUE_LABELS:' "$file" || true)
            if [[ -n "$LABELS_LINE" ]]; then
              LABELS=$(echo "$LABELS_LINE" | sed 's/^ISSUE_LABELS:[[:space:]]*//' | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | paste -sd, -)
              echo "🏷️ 获取到的标签：'$LABELS'"
            else
              LABELS=""
              echo "🏷️ 没有找到 ISSUE_LABELS，跳过添加标签"
            fi

            BODY=$(grep -v '^ISSUE_LABELS:' "$file")

            ISSUE_NUMBER=$(gh issue list \
              --state all \
              --search "$TITLE in:title" \
              --json number,title \
              | jq -r ".[] | select(.title==\"$TITLE\") | .number")

            if [[ -n "$ISSUE_NUMBER" ]]; then
              echo "♻️ 更新已存在的 issue #$ISSUE_NUMBER"
              if [[ -n "$LABELS" ]]; then
                gh issue edit "$ISSUE_NUMBER" --body "$BODY" --add-label "$LABELS"
              else
                gh issue edit "$ISSUE_NUMBER" --body "$BODY"
              fi
            else
              echo "🆕 创建新的 issue: $TITLE"
              if [[ -n "$LABELS" ]]; then
                gh issue create -t "$TITLE" -b "$BODY" -l "$LABELS"
              else
                gh issue create -t "$TITLE" -b "$BODY"
              fi
            fi
            
            echo "✅ 完成：$TITLE"
          done