name: Publish Issues

on:
  push:
    paths:
      - 'issues/*.md'

permissions:
  contents: read
  issues: write

jobs:
  publish_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Create or update GitHub Issues from markdown
        run: |
          echo "📂 开始处理 issues/*.md 文件"

          for file in issues/*.md; do
            TITLE=$(basename "$file" .md | sed 's/[-_]/ /g')

            # 读取第一行标签（如果有）
            FIRST_LINE=$(head -n 1 "$file")
            if [[ "$FIRST_LINE" == ISSUE_LABELS:* ]]; then
              LABELS=$(echo "$FIRST_LINE" | sed 's/^ISSUE_LABELS:[[:space:]]*//')
              BODY=$(tail -n +2 "$file")
            else
              LABELS=""
              BODY=$(cat "$file")
            fi

            echo "🔍 检查是否已有同名 issue: '$TITLE'"
            echo "🔍 检查获取到的标签：'$LABELS'"
            ISSUE_NUMBER=$(gh issue list \
              --state all \
              --search "$TITLE in:title" \
              --json number,title \
              | jq -r ".[] | select(.title==\"$TITLE\") | .number")

            if [[ -n "$ISSUE_NUMBER" ]]; then
              echo "♻️ 更新已存在的 issue #$ISSUE_NUMBER"
              if [[ -n "$LABELS" ]]; then
                gh issue edit "$ISSUE_NUMBER" --body "$BODY" --add-label "$LABELS"
              else
                gh issue edit "$ISSUE_NUMBER" --body "$BODY"
              fi
            else
              echo "🆕 创建新的 issue: $TITLE"
              if [[ -n "$LABELS" ]]; then
                gh issue create -t "$TITLE" -b "$BODY" --label "$LABELS"
              else
                gh issue create -t "$TITLE" -b "$BODY"
              fi
            fi
          done
        env:
          GH_TOKEN: ${{ github.token }}
