name: Publish Markdown as GitHub Issue

on:
  push:
    paths:
      - 'issues/*.md'

permissions:
  contents: read
  issues: write

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create issues from markdown
        run: |
          for file in issues/*.md; do
            FILENAME=$(basename "$file" .md)
            TITLE="$FILENAME"
            BODY=$(cat "$file")
            echo "📄 创建 Issue: $TITLE"
            gh issue create -R ${{ github.repository }} -t "$TITLE" -b "$BODY"
          done
        env:
          GH_TOKEN: ${{ github.token }}
