name: Publish Markdown as GitHub Issue

on:
  push:
    paths:
      - 'issues/*.md'

permissions:
  contents: read
  issues: write

jobs:
  create_or_update_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Create or update issues from markdown
        run: |
          for file in issues/*.md; do
            TITLE=$(basename "$file" .md | sed 's/[-_]/ /g')
            BODY=$(cat "$file")

            echo "🔍 检查是否已有同名 issue: '$TITLE'"
            ISSUE_NUMBER=$(gh issue list \
              --state all \
              --search "$TITLE in:title" \
              --json number,title \
              | jq -r ".[] | select(.title==\"$TITLE\") | .number")

            if [[ -n "$ISSUE_NUMBER" ]]; then
              echo "♻️ 更新已存在的 issue #$ISSUE_NUMBER"
              gh issue edit "$ISSUE_NUMBER" --body "$BODY"
            else
              echo "🆕 创建新的 issue: $TITLE"
              gh issue create -t "$TITLE" -b "$BODY"
            fi
          done
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 🔁 Trigger Build Gmeek Workflow
        run: |
          echo "🚀 正在触发 Build Gmeek workflow..."
          gh workflow run "Build Gmeek"
        env:
          GH_TOKEN: ${{ github.token }}
